src/Entity/Personnality.php
<?php

namespace App\Entity;

use App\Repository\PersonnalityRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PersonnalityRepository::class)
 */
class Personnality
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $music;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $movie;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $book;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $favorite_activity;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMusic(): ?string
    {
        return $this->music;
    }

    public function setMusic(string $music): self
    {
        $this->music = $music;

        return $this;
    }

    public function getMovie(): ?string
    {
        return $this->movie;
    }

    public function setMovie(string $movie): self
    {
        $this->movie = $movie;

        return $this;
    }

    public function getBook(): ?string
    {
        return $this->book;
    }

    public function setBook(string $book): self
    {
        $this->book = $book;

        return $this;
    }

    public function getFavoriteActivity(): ?string
    {
        return $this->favorite_activity;
    }

    public function setFavoriteActivity(string $favorite_activity): self
    {
        $this->favorite_activity = $favorite_activity;

        return $this;
    }
}

src/Entity/Physical.php
<?php

namespace App\Entity;

use App\Repository\PhysicalRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PhysicalRepository::class)
 */
class Physical
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $birthday;

    /**
     * @ORM\Column(type="boolean")
     */
    private $gender;

    /**
     * @ORM\Column(type="float")
     */
    private $height;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hair_color;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $eyes_color;

    /**
     * @ORM\Column(type="float")
     */
    private $weight;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBirthday(): ?\DateTimeInterface
    {
        return $this->birthday;
    }

    public function setBirthday(?\DateTimeInterface $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getGender(): ?bool
    {
        return $this->gender;
    }

    public function setGender(bool $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getHeight(): ?float
    {
        return $this->height;
    }

    public function setHeight(float $height): self
    {
        $this->height = $height;

        return $this;
    }

    public function getHairColor(): ?string
    {
        return $this->hair_color;
    }

    public function setHairColor(string $hair_color): self
    {
        $this->hair_color = $hair_color;

        return $this;
    }

    public function getEyesColor(): ?string
    {
        return $this->eyes_color;
    }

    public function setEyesColor(string $eyes_color): self
    {
        $this->eyes_color = $eyes_color;

        return $this;
    }

    public function getWeight(): ?float
    {
        return $this->weight;
    }

    public function setWeight(float $weight): self
    {
        $this->weight = $weight;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\ManyToOne(targetEntity=Physical::class, cascade={"persist", "remove"})
     */
    private $physical;

    /**
     * @ORM\ManyToOne(targetEntity=Personnality::class, cascade={"persist", "remove"})
     */
    private $personnality;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPhysical(): ?Physical
    {
        return $this->physical;
    }

    public function setPhysical(?Physical $physical): self
    {
        $this->physical = $physical;

        return $this;
    }

    public function getPersonnality(): ?Personnality
    {
        return $this->personnality;
    }

    public function setPersonnality(?Personnality $personnality): self
    {
        $this->personnality = $personnality;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'Pseudo',
                'attr' => [
                    'placeholder' => 'Votre nouveau pseudo '
                ]
            ])
            ->add('description', TextareaType::class, [
                'attr' => [
                    'placeholder' => 'Une citation ? Décrivez vous !'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

// essai pour git

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Form\UserType;
use App\Form\PhysicalType;
use App\Manager\UserManager;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class UserController extends AbstractController
{
    protected $em;

    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
    }

    
    /**
     * @Route("/user", name="user_index")
     */
    public function index()
    {
        $user = $this->getUser();

        return $this->render('user/index.html.twig', [
            'user' => $user
        ]);
    }

     /**
      * @Route("/user/edit", name="user_edit")
      */
    public function editUserAction(Request $request)
    {
        
       $user = $this->getUser();
        
       if (!$user)
       {
           throw new NotFoundHttpException("L'utilisateur n'existe pas");
       }

       $form = $this->createForm(UserType::class, $user);       

       $form->handleRequest($request);
       if ($form->isSubmitted() && $form->isValid()) {
            $this->em->flush();

        return $this->redirectToRoute('user_index', []);
    }

      return $this->render('user/edit.html.twig', [
          'user' => $user,
          'form' => $form->createView(),
      ]);
    }

    /**
     * @Route("profile/user/{id}", name="user_show", priority=-1)
     */
    public function showUserAction($id, UserRepository $userRepository) 
    {
        $user = $userRepository->findOneBy([
            'id' => $id
        ]);

        if(!$user) {
            $this->createNotFoundException("l'utilisateur n'existe pas ! ");
        }

        return $this->render('user/show.html.twig', [
            'user'=> $user
        ]);
    }

}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editer mon profil {% endblock %}

{% block body %}
<p> Mes informations :</p>
<div class="form">
    {{form_start(form)}}
    {{form_errors(form)}}

    {{form_row(form.name)}}

    {{form_row(form.description) }}

    <button type="submit" class="btn btn-secondary mt-4">
        Valider
    </button>
    {{form_end(form)}}

    
</div>
<hr>

{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon profil{% endblock %}

{% block body %}
<div class="align-middle">
    <div class="name">
        <h4>
            {{ user.name}} |

            {% if user.physical.gender == true  %}
            <span class="badge rounded-pill bg-primary">Femme</span>
            {% else %}
            <span class="badge rounded-pill bg-primary">Homme</span>
            {% endif %}
        </h4>
        <p>{% if user.physical.gender == true  %}
                née le {{user.physical.birthday|date}}
            {% else %}
                né le {{user.physical.birthday|date}}
            {% endif %}
        </p>
    </div>
    <hr>

    <p class="card-text"> {{ user.description }}</p>

    <hr>
    <div class="physical">
        <p><b>Taille</b> : {{ user.physical.height}} cm </p>
        <p><b>Poids</b>  {{ user.physical.weight }} kg</p>

        <p><b>Couleur des cheveux</b> : {{ user.physical.hairColor }}</p>
        <p><b>Couleur des yeux</b> : {{ user.physical.eyesColor }}</p>

    </div>

    <hr>
    <div class="personnality">
        <p><b>Musique préférée</b> : {{ user.personnality.music}} </p>
        <p><b>Film préféré</b> : {{ user.personnality.movie }} </p>

        <p><b>Livre préféré</b> : {{ user.personnality.book }}</p>
        <p><b>Activité préférée</b> : {{ user.personnality.favoriteActivity }}</p>

    </div>
    <hr>


</div>




<a href="{{ '/user/edit' }}" class="btn btn-primary">Modifier Pseudo/Description</a>
<a href="{{path('physical_edit', {'id' : user.physical.id})}}" class="btn btn-primary">Modifier la partie Physique</a>
    
    <a href="{{path('personnality_edit', {'id' : user.personnality.id})}}" class="btn btn-primary">Modifier la partie Personnalité</a>
{% endblock %}

templates/user/show.html.twig
{% extends "base.html.twig" %}

{% block title %}
Profile de : {{ user.name}}
{% endblock %}

{% block body %}
<section>
    <h1>{{ user.name }}</h1>
    <div class="information">
        <table class="table table-hover">

            <thead>
                <th scope="col">date de naissance</th>
                <th scope="col">sexe </th>
                <th scope="col">taille (cm)</th>
                <th scope="col">couleur des cheveux </th>
                <th scope="col">couleurs des yeux </th>
                <th scope="col">poids (Kg)</th>
            </thead>
            <tbody>
                <tr class="table-active table-primary">
                    <th scope="row">{{ user.physical.birthday|date }}</th>
                    {% if user.physical.gender == true %}
                    <th>femme</th>
                    {% else %}
                        <th>Homme</th>
                    {% endif %}
                    <th>{{ user.physical.height }}</th>
                    <th>{{ user.physical.hairColor }}</th>
                    <th>{{ user.physical.eyesColor }}</th>
                    <th>{{ user.physical.weight }}</th>
                </tr>
            </tbody>
        </table>

        <p>Musique préférée : <b> {{user.personnality.music}} </b> </p>
        <p>Film préféré : <b> {{user.personnality.movie}} </b> </p>
        <p>Livre préféré : <b> {{user.personnality.book}} </b> </p>
        <p>Activitée préférée : <b> {{user.personnality.favoriteActivity}} </b> </p>
    </div>
</section>
{% endblock %}